version: "3.9"
services:
    web:
        image: loicsharma/baget
        container_name: tonybark_nuget
        restart: always
        ports:
          - "5555:5555"
        volumes:
          - "nuget:/var/baget/packages"
          - "nuget:/var/baget/baget.db"
        env_file:
            - beget.env
            - secrets.env # "ApiKey" variable is located here
    nginx: 
        image: nginx:latest
        restart: always
        container_name: tonybark_nuget_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/:/etc/letsencrypt/
        links:
          - "web"
volumes:
    nuget: